version: '3.1'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on: 
      - db
      - memcached
    volumes:
      - ./src:/var/www/html/
    env_file: env_vars/webapp_env_vars.env
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  memcached:
    image: memcached
    ports:
      - 45001:11211

  
volumes: 
  mysql-data: