version: '3.1'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on: 
      - db
    volumes:
      - ./src:/var/www/html/
    env_file: env_vars/webapp_env_vars.env
    
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    ports:
      - "4000:4000"

  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  memcached:
    container_name: mymemcached
    image: memcached:latest
    ports:
      - "11211:11211"
  
volumes: 
  mysql-data: